name: ci

on: push

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          rustc --version
          clang++ --version

      - name: Distro setup
        run: |
          sudo apt install -y ninja-build
          pip install conan
          bash ci/setup_gbench.sh

      - name: Compile and Run
        run: |
          make configure
          make build
          make run
